version: "3"

services:
  database:
    image: postgres:16.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    image: p21-desafio-app
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
      - /app/node_modules/
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: library
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      - database

volumes:
  database:
